package com.gauravbytes.springjdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.PreparedStatementCallback;

class GeneratedKeysPreparedStatementCallback implements PreparedStatementCallback<Integer> {

	@Override
	public Integer doInPreparedStatement(PreparedStatement ps) throws SQLException {
		int updated = ps.executeUpdate();
		if (updated > 0) {
			try (ResultSet rs = ps.getGeneratedKeys()) {
				if (rs.next())
					return rs.getInt("id");
			}
			throw new SQLException("There was no key auto generated by the database");
		}
		throw new SQLException("Nothing was updated");
	}
}