/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gauravbytes.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SEX {
  MALE, FEMALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SEX\",\"namespace\":\"com.gauravbytes.avro\",\"symbols\":[\"MALE\",\"FEMALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
